In [1]:
import numpy as np

In [38]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 1],
    [3, 1, 2, 1]
])

In [39]:
V = np.array([
    [2, 4],
    [1, 2],
    [3, 1],
    [4, 5]
])

In [34]:
U.shape, V.shape

((3, 4), (4, 2))

### Dot product
$$\sum_{i=0}^{n-1} u_i v_i$$

In [25]:


def vector_vector_mul(u, v):
    assert u.shape[0] == v.shape[0]

    result = 0
    for i in range(u.shape[0]):
        result += u[i] * v[i]

    return result

In [26]:
u = np.array([2, 3, 1, 2])
v = np.array([0, 1, 1, 5])
res = vector_vector_mul(u, v)
print(res)

14


In [27]:
print(u.dot(v))

14


In [31]:
# Matrix Vector multiplication 

In [29]:
def matrix_vector_mul(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] += vector_vector_mul(U[i], v)

    return result
    

In [30]:
print(matrix_vector_mul(U, v))

[39.  8.  8.]


In [32]:
# Matrix matrix multiplication or Cross Product 

In [46]:
def matrix_matrix_mul(U, V):
    assert U.shape[1] == V.shape[0]

    m = U.shape[0]
    n = V.shape[1]

    result = np.zeros((m, n))

    for i in range(n):
        vi = V[:, i]
        Uvi = matrix_vector_mul(U, vi)
        result[:, i] = Uvi

    return result

    

In [48]:
matrix_matrix_mul(U, V)

array([[47., 51.],
       [11., 14.],
       [17., 21.]])

In [49]:
U.dot(V)

array([[47, 51],
       [11, 14],
       [17, 21]])

In [50]:
# Identity matrix (Square matrix with diagonal 1)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# or 
I = np.eye(3)

In [58]:
Us = U[:, 0:3]

In [59]:
Us

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [68]:
Us.dot(I)

array([[2., 4., 5.],
       [1., 2., 1.],
       [3., 1., 2.]])

In [69]:
# Inverse
Us_inv = np.linalg.inv(Us)

In [70]:
Us_inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [72]:
Us_inv.dot(Us) # Results in an identity matrix

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])