In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/Caskroom/mambaforge/base/envs/mlzc/lib/python3.11/site-packages/numpy/__init__.py'>

## Creating Arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.full(10, 2.2)

array([2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2])

In [10]:
x = np.array([1, 34, 3, 23])
x

array([ 1, 34,  3, 23])

In [17]:
x[1]

np.int64(34)

In [19]:
x[2] = 22
print(x[2])

22


In [20]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [22]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Multi Dimensional Arrays

In [25]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
bigX = np.array([[1, 2, 3], [4, 5, 6]])
bigX


array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
bigX[0] # zero-based in numpy 

array([1, 2, 3])

In [31]:
print(bigX[1,2])

6


In [34]:
bigX[1]=[7, 8, 6]
bigX


array([[1, 2, 3],
       [7, 8, 6]])

In [50]:
bigX[0:1] # until second row => first row

array([[1, 2, 3]])

In [48]:
bigX[-2] # second last row

array([1, 2, 3])

###  Slicing 

In [47]:
# Pick second row from bigX
bigX[:, 1]

array([2, 8])

In [56]:
# First and third columns
bigX[:, (0,2)]

array([[1, 3],
       [7, 6]])

In [57]:
# Last 2 columns
bigX[:, 1:3]

array([[2, 3],
       [8, 6]])

## Randomnly generated arrays

In [68]:
100 * np.random.rand(4,3) # different with every exec

array([[13.45799453, 51.35781213, 18.44398656],
       [78.53351478, 85.39752926, 49.42368374],
       [84.65614854,  7.9645477 , 50.52460901],
       [ 6.52865044, 42.81223276,  9.65309157]])

In [67]:
np.random.seed(2) # same on every exec
np.random.randn(4,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801]])

In [69]:
np.random.randint(low=0, high=100, size=(3,2))

array([[80, 52],
       [76, 50],
       [ 4, 90]])

## Element wise ops

In [73]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [72]:
a * 2

array([0, 2, 4, 6, 8])

In [77]:
b = 3 + (a * 23) ** 2 
b

array([   3,  532, 2119, 4764, 8467])

In [78]:
a + b

array([   3,  533, 2121, 4767, 8471])

In [79]:
a > 3

array([False, False, False, False,  True])

In [82]:
(a + 10) > b

array([ True, False, False, False, False])

In [88]:
b[b > a ** 10]

array([   3,  532, 2119])

## Summarizing ops

In [90]:
a.min()

np.int64(0)

In [91]:
a.max()

np.int64(4)

In [92]:
b.mean()

np.float64(3177.0)

In [93]:
b.std()

np.float64(3120.651662714056)

In [94]:
a.sum()

np.int64(10)